products = [
    {
      '_id': '1',
      'name': 'Saharian Wind',
      'image': '/images/parfum1.jpg',
      'description':
        'Inspired by the beauty of the Sahara and enamoured of freedom, Saharian Wind, like a memory, reminds us of a warm breath of burning, velvety dust, sun-warmed skin, a vibrant and troubling solitary adventure. An enchanting and luminous fragrance, created with love and audacity',
      'brand': 'Vlab13',
      'category': 'Man',
      'price': 89.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Herbal Aquatica',
      'image': '/images/parfum2.jpg',
      'description':
        'The freshness of an early evening where the slightly mentholated spray transports us to the heart of Ancient Egypt. Herbal Aquatica, an undeniable treasure.',
      'brand': 'Vlab13',
      'category': 'Women',
      'price': 99.99,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Wave Musk',
      'image': '/images/parfum3.jpg',
      'description':
        'A powerful ocean wave with notes of salt and white musk is exploding over driftwood and seaweed. The freshness of this very marine perfume is supported by grapefruit and orange blossom.',
      'brand': 'Vlab13',
      'category': 'Man',
      'price': 89.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'Tropical Wood',
      'image': '/images/parfum4.jpg',
      'description':
        'A joyful combination of Bergamot, Passion Fruit and Pineapple, infused by strong spirited Aoud from Malaysia, shines on a titillating duo of Rose from Bulgaria and enthralling Violet, and diffuses a chic sillage of Rich Leather, White Musk and Vanilla from Madagascar.',
      'brand': 'Vlab13',
      'category': 'Women',
      'price': 99.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Beach Walk',
      'image': '/images/parfum5.jpg',
      'description':
        'With radiant notes of bergamot and ylang-ylang, Beach Walk perfume evokes memories of summer days spent on sandy beaches. Notes of coconut milk and musk envelop you in the warming sensation of sun-kissed skin.',
      'brand': 'Vlab13',
      'category': 'Man',
      'price': 89.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Kumkat Wood',
      'image': '/images/parfum6.jpg',
      'description':
        'This sophisticated perfume is a perfect choice for an everyday scent especially during the warm months. With a combination of citrusy freshness from grapefruit and bergamot combined with oriental notes of spices and the heart hide delicate, floral notes, fragrant patchouli and deep amber.',
      'brand': 'Vlab13',
      'category': 'Woman',
      'price': 99.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  ]